### ISSUE TITLE
Document basic use cases

### ISSUE THREAD

**Issue by nichtich** [gbv/login-server#11]
The application of login-server is a complex matter. This should be documented with a diagram to show

* Identity providers (e.g. ORCID)
* Service providers (e.g. jskos-server, Wikidata-write-access...)
* clients/applications (Cocoda)

[Many such diagrams and explanations exist](https://www.google.com/search?q=%22Identity+provider%22+%22service+provider%22&tbm=isch) but it is still confusing.

**Comment by stefandesu** [comment]
I also though about creating a small example on CodePen to demonstrate the workflow of using this in a web application.

**Comment by nichtich** [comment]
The [login-client](https://github.com/gbv/login-client) is a good example to be integrated. Usage, motivation, and background should be explain anyhow. I started in the Usage section of README and will extend once the APIs are stable and when we have a client.

**Comment by nichtich** [comment]
We could serve an additional web interface at `/api` with short description of the programmable APIs and possibly login-client demo. A list of API endpoints as given in README.md is enough for milestone 1.0.0.

**Comment by nichtich** [comment]
Documentation is fine to start with version 1.0.0. See #27 for further/improved documentation.
