### ISSUE TITLE
Move general information text from /login to base (/)

### ISSUE THREAD

**Issue by nichtich** [gbv/login-server#14]

**Comment by stefandesu** [comment]
Should we make sure that a user sees that text at least once? If the text is only available at `/`, but someone would go directly to `/login`, they wouldn't see the text. Alternatively, we could add a one-liner like "By using this service, you agree that your data will be publicly available. For more information click here" that is on `/login` and links back to `/`.

**Comment by nichtich** [comment]
Yes, a fixed one-liner with link to `/` should be enough.
