### ISSUE TITLE
Let users mark accounts as public/non-public

### ISSUE THREAD

**Issue by nichtich** [gbv/login-server#15]
* [ ] add provider option `public` set to `true` (always), `false` (never) or `null` (user-defined). For instance VZG LDAP should be `false` (never public)
* [ ] add user field ~~`providerPublic`~~ `identities.*.public` that can be changed via `PATCH /users/:id` (e.g. `{"orcid":{"public": true}}`) when provider option is set to `null` (or not defined).
* [ ] make sure only public provider and URIs are accessible at `GET /users`

**Comment by stefandesu** [comment]
Question: If a certain provider, let's say ORCID, is set to user-defined, and a particular user has set it to `false`, should the user still be found when someone specifically searches for their ORCID iD via `/users?uri=https://orcid.org/id-of-that-user`?

**Comment by nichtich** [comment]
If an identity is not public, it should neither be searchable. The only method to find out about the non-public identity should be to authenticate with this identity.

**Comment by stefandesu** [comment]
The question is still whether we should even have all information publicly available. We'll decide that after integrating everything into Cocoda.

**Comment by stefandesu** [comment]
I'm closing this issue because if no information is publicly available anyway, there is no reason for individual identities to be private/public.
