### ISSUE TITLE
Detect and forbid multiple accounts with same identity

### ISSUE THREAD

**Issue by nichtich** [gbv/login-server#17]
The same identity (account + id) should not be allowed at multiple accounts. I managed to produce two account connected to the same GitHub identity. This can be done when a user tries to log in with a disconnected provider? Anyhow, an internal uniqueness check right before creating a new account and right before adding a new identity is needed.

I guess we need a method to merge accounts because this can always happen:

* user creates an account 1 with identity provider A
* user creates another account 2 with identity provider B
* user tries to connect identity B to account 1 (or identity A to account 2)

Merging will keep user name and id of the account that initiates the merge. The old account ID should be saved (e.g. in array field `mergedIds`) and lookup of the old user URI should redirect HTTP 301 to the new URI.

**Comment by stefandesu** [comment]
Should the merge happen automatically or should there be a prompt to ask the user whether to merge the accounts?

**Comment by stefandesu** [comment]
Update: If it is an easy merge (i.e. no conflicting identities), the merge should happen automatically, or maybe after a short user confirmation. If there is a conflict, a message should be shown that the user needs to disconnect the conflicted identity before being able to merge.

**Comment by stefandesu** [comment]
Merging users is now implemented (more info: https://github.com/gbv/login-server/commit/0fd2ba4a68842b37e3b9ea49ca31738427d4a04c).
