### ISSUE TITLE
Offer general information in /about?

### ISSUE THREAD

**Issue by stefandesu** [gbv/login-server#25]
Some kind of shortened version of the information available at [base (/)](https://coli-conc.gbv.de/login/) could also be made available through [/about](https://coli-conc.gbv.de/login/about) so that clients can display it. The question is whether to only use text or also provide HTML that can be directly used (only using simple markup like `<strong>` or `<br>`).

**Comment by nichtich** [comment]
I can think of:

* [ ] version number of login-server
* [ ] base URL
* URLs of
  * [ ] imprint (Impressum)
  * [ ] privacy policy
  * [ ] sources
* [ ] which domains the server can be used on (#22)

The textual description depends on context so don't include it.
