### ISSUE TITLE
Logout Usability Improvement

### ISSUE THREAD

**Issue by DennisTobola** [gbv/login-server#35]
If you try to log out, the first thing to catch your eye is a big red button "Delete User Account" while the logout is just a small blue word.

I would suggest changing the "Delete User Account"-button to one similar to the logout-button now, and the logout-button to one similar to the "Delete User Account"-button now.

**Comment by stefandesu** [comment]
I adjusted the buttons. If you have any further improvements in mind, feel free to reopen the issue.
