### ISSUE TITLE
Add easydb-provider

### ISSUE THREAD

**Issue by nichtich** [gbv/login-server#43]
Having several instances of [easydb](https://www.programmfabrik.de/easydb/), which don't support authentification via external backends, it would make sense to support easydb as provider (if possible). The [easydb api](https://docs.easydb.de/en/technical/api/) supports setting a new password but it is not clear whether authentification is possible without a hack.

**Comment by nichtich** [comment]
Seems easy: see easydb api endpoint [/session](https://docs.easydb.de/en/technical/api/session/) to get a token and /session/authenticate for authentification, followed by [/user](https://docs.easydb.de/en/technical/api/user) to get user `displayname` and [possibly other user data](https://docs.easydb.de/en/technical/types/user/).

**Comment by stefandesu** [comment]
I guess it should be easy enough to fork an existing passport strategy like [passport-github](https://github.com/jaredhanson/passport-github) and create a "passport-easydb" provider. I will look into it!

**Comment by stefandesu** [comment]
If there are multiple easydb instances which should be supported, we could add an option for providers to have multiple URLs and on the site where the user types in their credentials, they can choose which instance to authenticate against. This way, we wouldn't need to add a separate provider entry for each instance.

**Comment by stefandesu** [comment]
I received a test account for an easydb instance and managed to authenticate, so I could try to implement this as a provider now. 👌

> If there are multiple easydb instances which should be supported, we could add an option for providers to have multiple URLs and on the site where the user types in their credentials, they can choose which instance to authenticate against. This way, we wouldn't need to add a separate provider entry for each instance.

@nichtich What do you say about this?

**Comment by stefandesu** [comment]
I have now created [passport-easydb](https://github.com/gbv/passport-easydb). This first version already works, but it has no tests or proper error handling (although error types are already defined based on the easydb API). 

To try it out locally, you need access to an easydb instance and account credentials for it.

1. Install passport-easydb from GitHub (not yet on NPM):
```bash
npm install gbv/passport-easydb
```

2. Add easydb strategy in `strategies/easydb.js`:
```js
/**
 * easydb Stategy.
 */

const Strategy = require("passport-easydb")

module.exports = (options, provider, callback) => new Strategy(options, (req, accessToken, refreshToken, profile, done) => {
  callback(req, null, null, {
    id: profile.id,
    name: profile.displayName,
    username: profile.username,
    token: accessToken,
    provider: provider.id
  }, done)
})
```

3. Add strategy to your `providers.json`:
```json
  {
    "id": "easydb",
    "name": "easydb test provider",
    "strategy": "easydb",
    "credentialsNecessary": true,
    "options": {
      "url": "https://easydb5-test.example.com/api/v1/"
    }
  }
```

4. easydb should now be an option for login (or to connect with an existing account).

**Comment by stefandesu** [comment]
I just updated `passport-easydb` and released it on npm even though it still has no tests or proper error handling. However, the integration works and wrong credentials are already properly handled. I think this could be merged already.
