### ISSUE TITLE
Add default name?

### ISSUE THREAD

**Issue by stefandesu** [gbv/login-server#44]
If a person creates an account and the first provider they use doesn't return a display name, the user's account name will likely be empty. This causes problems especially for Cocoda (https://github.com/gbv/cocoda/issues/521). Should we configure a default name for every user? Or maybe something fun like Google's anonymous names when editing a document?

**Comment by nichtich** [comment]
We could use as default fallback if there is no display name:

* always "{provider} user", or
* the local identifier (part of the URI after the last `/`), or
* both combined "{localid}@{provider}" or "{provider} user {localid}"

**Comment by stefandesu** [comment]
I opted for username/id@provider (there should be either a username or an id for every provider, so no need to deconstruct the URI or something).
