### ISSUE TITLE
Clarify at login that a new account will be created

### ISSUE THREAD

**Issue by stefandesu** [gbv/login-server#48]
Specifically mention that the user first has to log into the existing account before connecting an additional identity. The purpose is to prevent users from accidentally creating two separate accounts instead of one account with two identities.

**Comment by stefandesu** [comment]
If a user logs into an account which is not yet connected to an existing user account (i.e. a new account would be created), we could add an additional page that does something like the following:

- Login via {Provider X} was successful; no active user account was found. Button: Create Account
- Alternatively, log into other provider and connect the account for {Provider X} with an existing user account.

The second part might not be easy to implement because we will have to temporarily save the data from {Provider X} somewhere, but it should be possible with the session.

**Comment by stefandesu** [comment]
Since this issue requires some changes in application flow (as mentioned in my previous comment), I would suggest moving it to 0.5.0 (or maybe to a 0.4.1).

**Comment by stefandesu** [comment]
I wonder if this is really necessary. It already says on the login page:

> If necessary, a new user account will be created on first login. 

The only use case I can think of is when a user logs in with a different provider than previously and now has two accounts. However, how often does that happen, and is it really such a big problem?

I would vote for not changing this. Maybe we can simply add another sentence like "To connect an additional provider to your existing account, please log into that existing account first."

@nichtich ?

**Comment by nichtich** [comment]
Not required as accounts get merged if used with same identity.
