### ISSUE TITLE
Show list of supported client applications

### ISSUE THREAD

**Issue by nichtich** [gbv/login-server#72]
In addition to #70 show supported client applications without active session and assign names to active sessions. This requires an additional config file `applications.json`: 

~~~json
[
  { "url": "//bartoc.org/", "name": "BARTOC" },
  { "url": "//coli-conc.gbv.de/cocoda/", "name": "Cocoda" },
  { "url": "//coli-conc.gbv.de/coli-rich/", "name": "coli-rich" }
]
~~~

Some sessions can be mapped to applications to show their name instead of the URL.

**Comment by stefandesu** [comment]
If we add an `applications.json` file, we have two options:
1. Either we don't commit it into the repo, thus every instance needs to provide its own file,
2. or we do commit it, but there's no easy way of adding additional applications.

I tend towards 1. In theory, we could have a default set of applications (either hardcoded or in a `applications.default.json`). What do you think?

**Comment by nichtich** [comment]
`ALLOWED_ORIGINS` has no default value neither, so 

3. The list of applications is empty if no `applications.json` exists.

**Comment by stefandesu** [comment]
> The list of applications is empty if no `applications.json` exists.

So 1. 😉 The default set was just a thought and basically my number 3.
