### ISSUE TITLE
Add admin tool

### ISSUE THREAD

**Issue by nichtich** [gbv/login-server#81]
Via command line (should be enough to start with) and/or web interface and API (restricted to selected admin identities). Required to

* lookup a user by one of its uris
* provide statistics (number of accounts, number of provider identities, number of active accounts...)

The first is basically a thin wrapper around `db.users.find(...)`. A dump of *all* users could also be used to generate basic statistics with `jq` on the command line-

**Comment by stefandesu** [comment]
I had implemented something like this in the past as a CLI script: `./bin/list-users.js`. I have now adjusted it slightly and it should be enough for this use case, especially when working with `jq` as well.
